use_frameworks!
platform :ios, '10.0'

target 'RxTapAction_Example' do
  pod 'RxTapAction', :path => '../'
  pod 'Reusable'
  pod 'RxDataSources'
  pod 'SnapKit'

  target 'RxTapAction_Tests' do
    inherit! :search_paths

    
  end
end
